# Generated by Django 2.1.4 on 2018-12-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Hunt Name')),
                ('last_update', models.DateTimeField(verbose_name='Last Updated')),
                ('active', models.SmallIntegerField(verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Puzzle Name')),
                ('last_update', models.DateTimeField(verbose_name='Last Updated')),
                ('isMeta', models.SmallIntegerField(verbose_name='Metapuzzle')),
                ('active', models.SmallIntegerField(verbose_name='Active')),
                ('url', models.URLField(verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='PuzzRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzid', models.IntegerField(verbose_name='Puzzle')),
                ('roundid', models.IntegerField(verbose_name='Round')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Round Name')),
                ('last_update', models.DateTimeField(verbose_name='Last Updated')),
                ('active', models.SmallIntegerField(verbose_name='Active')),
            ],
        ),
    ]
