# Generated by Django 2.1.4 on 2018-12-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0002_auto_20181218_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=120, verbose_name='Round Name')),
                ('last_update', models.DateTimeField(verbose_name='Last Updated')),
                ('puzzid', models.IntegerField(default='0', verbose_name='Hunt ID')),
            ],
        ),
    ]
