# Generated by Django 2.1.4 on 2018-12-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0003_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='puzzround',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
