# Generated by Django 2.1.4 on 2018-12-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0004_auto_20181218_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hunt',
            old_name='id',
            new_name='huntid',
        ),
        migrations.RenameField(
            model_name='puzzle',
            old_name='id',
            new_name='puzzid',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='id',
            new_name='roundid',
        ),
    ]
