# Generated by Django 2.1.4 on 2018-12-18 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0006_auto_20181218_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answerid', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=120, verbose_name='Round Name')),
                ('last_update', models.DateTimeField(verbose_name='Last Updated')),
                ('puzzid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hunts.Puzzle')),
            ],
        ),
    ]
