# Generated by Django 2.1.4 on 2018-12-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0008_auto_20181219_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='discordchannelid',
            field=models.IntegerField(default='0', verbose_name='Discord ID'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='googlesheet',
            field=models.CharField(max_length=120, null=True, verbose_name='Google Sheets Link'),
        ),
    ]
