# Generated by Django 2.1.4 on 2018-12-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0009_auto_20181219_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='discordchannelid',
            field=models.BigIntegerField(default='0', verbose_name='Discord ID'),
        ),
    ]
