# Generated by Django 2.1.4 on 2018-12-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0010_auto_20181219_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='priority',
            field=models.SmallIntegerField(default='0', verbose_name='Priority'),
        ),
    ]
