# Generated by Django 2.1.4 on 2018-12-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0011_puzzle_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='discordchannelid',
            field=models.BigIntegerField(default='0', verbose_name='Discord ID'),
        ),
    ]
