# Generated by Django 2.1.4 on 2018-12-22 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0013_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='puzzid',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
