# Generated by Django 2.1.4 on 2018-12-22 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='puzzid',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
