# Generated by Django 2.1.4 on 2018-12-22 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hunts', '0014_auto_20181222_0222'),
        ('puzzle', '0002_auto_20181222_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagid', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=120, verbose_name='Tag')),
                ('puzzid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hunts.Puzzle')),
            ],
        ),
    ]
