# Generated by Django 2.1.4 on 2018-12-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0003_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='puzzid',
        ),
        migrations.AddField(
            model_name='tag',
            name='puzzid_id',
            field=models.IntegerField(null=True),
        ),
    ]
